global AppList := []
global AppAlt := []

app := AppList["REPLACEMEPLEASE.exe"] := []
 app[1] := ""
 app[2] := ""
 app[3] := ""
 app[4] := ""
 app[5] := ""
 app[6] := ""
 app[7] := ""
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["javaw.exe"] := []
 app[1] := ""
 app[2] := ""
 app[3] := "MMove 0 -500 0 R"
 app[4] := ""
 app[5] := ""
 app[6] := ""
 app[7] := ""
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["Firefox.exe"] := []
 app[1] := "Scroll 6"
 app[2] := "Scroll -6"
 app[3] := "^{pgup}"
 app[4] := "^{pgdn}"
 app[5] := "^+{t}"
 app[6] := "!{d}"
 app[7] := "^+{p}"
 app[8] := "^+{t}"
app[9] := "{f}"
app[10] := ""
app[13] := "!{d}, ^{c}, Focus WindowsTerminal, CycleActiveWindow, SleepMoment 2, {.}, {/}, {y}, {t}, {tab}, {space}, {'}, ^{v}, {'}, {enter}, SleepMoment 5, Focus firefox"

; app[8] := "{down}, {down}, {right}, {down}, {down}, {right}, {down}, {down}, {down}, {down}, {right}, {down}, {down}, {down}, {down}, {right}, {down}, {down}, {down}, {right}, {down}, {down}, {right}, {down}, {down}, {right}, {down}, {right}, {down}, {right}, {down}, {right}, {down}, {right}, {down}"
;  {down}, {right}, {down}, {right}, {down}, {down}, {down}, {right}, {down}, {down}, {down}, {right}"
 ;
;"{down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}, {down}"
;"^+{p}"
;app[8] := "!{d}, ^{c}, !{tab}"
;"{right}, {down}, {right}, {down}, {down}, {down}, {down}, {right}, {down}, {down}, {right}, {down}, {down}, {down}, {right}, {down}, {down}, {down}, {right}, {down}, {down}, {down}, {right}, {down}, {right}, {down}, {down}"
;"!{d}, ^{c}, !{tab}"
;app[9] := "^+{i}"  
;app[10] := "{down}, {down}, {right}, {down}, {down}, {down}, {right}, {down}, {down}, {down}, {right}, {down}, {down}, {down}, {right}, {down}, {right}, {down}, {right}, {down}, {right}, {down}, {right}, {down}, {down}, {right}, {down}, {enter}, {tab}, {tab}, {enter}, {left}, {left}, {left}, {left}, {left}, {delete}, {delete}, {delete}, {delete}, {delete}, {end}, {backspace}, ^{a}, ^{a}, ^{a}, ^{a}, ^{c}, ^{t}, ^{v}, {enter}, !{a}, !{a}, !{a}, !{a}, !{a}, !{d}, ^{a}, ^{a}, ^{a}, ^{a}, ^{a}, ^{c}, !{tab}" ;{left}, {left}, {left}, {left}, {left}, {delete}, {delete}, {delete}, {delete}, ^{a}, 
;  {down}, {right}, {down}, {right}, {down}, {down}, {down}, {right}, {down}, {down}, {down}, {right}"
 ;

; app[5] := "SwitchToAlt 0"

app := AppList["WindowsTerminal.exe"] := []
 app[1] := "{up}"
 app[2] := "{down}"
 app[3] := "{left}"
 app[4] := "{right}"
 app[5] := "{escape}"
 app[6] := "{}"
 app[7] := "{enter}"
 app[8] := "cd downloads {enter}"
 app[9] := ""
app[10] := ""
app[11] := ""
;app[10] := "dl , ^{v}, {enter}"

app[10] := "dl {'}, ^{v}, {'}, {enter}"

app := AppList["WINWORD.EXE"] := []
 app[1] := "{up}"
 app[2] := "{down}"
 app[3] := "^{Left}"
 app[4] := "^{Right}"
 app[5] := "{pgup}"
 app[6] := "ToggleVar ShiftDown"
 app[7] := "{pgdn}"
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["Tobii.EyeTracking.Portal.WPF.exe"] := []
 app[1] := "{up}"
 app[2] := "{down}"
 app[3] := "^{Left}"
 app[4] := "^{Right}"
 app[5] := "foo"
 app[6] := "foo"
 app[7] := "foo"
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["FSViewer.exe"] := []
 app[1] := "{up}"
 app[2] := "{down}"
 app[3] := "{Left}"
 app[4] := "{Right}"
 app[5] := "{esc}"
 app[6] := "{space}"
 app[7] := "{enter}"
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := "{pgup}"
app[12] := "{pgdn}"

app := AppList["Explorer.exe"] := []
 app[1] := "{up}"
 app[2] := "{down}"
 app[3] := "{left}"
 app[4] := "{right}"
 app[5] := "!{left}"
 app[6] := "#{e}"
 app[7] := "Delay {enter}"
 app[8] := "^+{1}"
 app[9] := "!{d} wt {enter}"
app[10] := "^+{6}"
app[11] := "{pgup}"
app[12] := "{pgdn}"

app := AppList["devenv.exe"] := []
 app[1] := "{up}"
 app[2] := "{down}"
 app[3] := "{left}"
 app[4] := "{right}"
 app[5] := "^{pgup}"
 app[6] := "ToggleVar ShiftDown"
 app[7] := "^{pgdn}"
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["Code.exe"] := []
 app[1] := "{up}"
 app[2] := "{down}"
 app[3] := "{left}"
 app[4] := "{right}"
 app[5] := "^{pgup}"
 app[6] := "^{left}"
 app[7] := "^^{pgdn}"
 app[8] := "ToggleVar CtrlDown"
 app[9] := "ToggleVar ShiftDown"
 app[10] := "ToggleVar ShiftDown, ToggleVar CtrlDown"
 app[11] := ""
app[12] := ""

app := AppList["POWERPNT.EXE"] := []
 app[1] := ""
 app[2] := ""
 app[3] := ""
 app[4] := ""
 app[5] := "{up}"
 app[6] := ""
 app[7] := "{down}"
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["SumatraPDF.exe"] := []
 app[1] := "" ;+{F3}"
 app[2] := "" ;{F3}"
 app[3] := "{left}"
 app[4] := "{right}"
 app[5] := "^{7}"
 app[6] := "{F11}"
 app[7] := "^{8}"
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["ApplicationFrameHost.exe"] := []
 app[1] := "+{F3}"
 app[2] := "{F3}"
 app[3] := "{left}"
 app[4] := "{right}"
 app[5] := "^{7}"
 app[6] := "{F11}"
 app[7] := "^{8}"
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["nomacs.exe"] := []
 app[1] := "Scroll 4"
 app[2] := "Scroll -4"
 app[3] := "{left}"
 app[4] := "{right}"
 app[5] := "{=}"
 app[6] := "{}"
 app[7] := "{-}"
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["notepad++.exe"] := []
 app[1] := "" ;{up}"
 app[2] := "" ;{down}"
 app[3] := "" ;{left}"
 app[4] := "" ;{right}"
 app[5] := "^{pgup}"
 app[6] := "ToggleVar ShiftDown"
 app[7] := "^{pgdn}"
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["LINQPad7.exe"] := []
 app[1] := "{up}"
 app[2] := "{down}"
 app[3] := "{left}"
 app[4] := "{right}"
 app[5] := "^{pgup}"
 app[6] := "ToggleVar ShiftDown"
 app[7] := "^{pgdn}"
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["Acrobat.exe"] := []
 app[1] := "{up}"
 app[2] := "{down}"
 app[3] := "{left}"
 app[4] := "{right}"
 app[5] := "^{tab}"
 app[6] := "ToggleVar ShiftDown"
 app[7] := "^+{tab}"
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["VLC.exe"] := []
 app[1] := "{left}"
 app[2] := "{right}"
 app[3] := "^{left}"
 app[4] := "^{right}"
 app[5] := "{p}"
 app[6] := "{space}"
 app[7] := "{n}"
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["Reason.exe"] := []
 app[1] := "MDrag 0 4 0 R"
 app[2] := "MDrag 0 -4 0 R"
 app[3] := "MDrag 0 20 0 R"
 app[4] := "MDrag 0 -20 0 R"
 app[5] := "{f5}"
 app[6] := "{f6}"
 app[7] := "{f7}"
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["Bitwig Studio.exe"] := []
 app[3] := ""
 app[4] := ""
 app[1] := ""
 app[2] := ""
 app[5] := "{up}"
 app[6] := ""
 app[7] := "{down}"
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := AppList["Zoom.exe"] := []
 app[3] := ""
 app[4] := ""
 app[1] := ""
 app[2] := ""
 app[5] := ""
 app[6] := "!{a}"
 app[7] := ""
 app[8] := ""
 app[9] := ""
app[10] := ""
app[11] := ""
app[12] := ""

app := Applist["BitwigPluginHost-X64-SSE41.exe"] := Applist["Bitwig Studio.exe"]